Repository Badlose/Starbank, pull requests merged in 2025-04, with the labels that each got.

#56 implemented a Management Controller, Service, and Info output
  bank/pom.xml
  bank/src/main/java/ru/starbank/bank/controller/ManagementController.java
  bank/src/main/java/ru/starbank/bank/dto/DynamicRecommendationDTO.java
  bank/src/main/java/ru/starbank/bank/dto/InfoDTO.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/ManagementServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/ManagementService.java
  bank/src/main/java/ru/starbank/bank/staticRecommendations/StaticRecommendationDBInitializer.java
  bank/src/test/java/ru/starbank/bank/cacheTest/CacheServiceTest.java
Labels: enhancement

#57 53 liquibase
  bank/pom.xml
  bank/src/main/java/ru/starbank/bank/model/DynamicRecommendation.java
  bank/src/main/java/ru/starbank/bank/model/Rule.java
  bank/src/main/resources/application.properties
  bank/src/main/resources/liquibase/script/changes.sql
Labels: Databse

#61 55 statistics
  bank/src/main/java/ru/starbank/bank/controller/RecommendationController.java
  bank/src/main/java/ru/starbank/bank/dto/StatisticsDTO.java
  bank/src/main/java/ru/starbank/bank/model/Statistic.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/RecommendationService.java
Labels: enhancement

#63 55 statistics
  bank/src/main/java/ru/starbank/bank/controller/RecommendationController.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectRuleQueryException.java
  bank/src/main/java/ru/starbank/bank/exceptions/SQLRequestException.java
  bank/src/main/java/ru/starbank/bank/exceptions/SqlRequestException.java
  bank/src/main/java/ru/starbank/bank/model/DynamicRecommendation.java
  bank/src/main/java/ru/starbank/bank/model/Rule.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationActiveUserOfRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationCheckerServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationUserOfRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/RecommendationRuleService.java
  bank/src/main/java/ru/starbank/bank/service/RecommendationService.java
  bank/src/main/java/ru/starbank/bank/service/RuleService.java
  bank/src/main/java/ru/starbank/bank/staticRecommendations/StaticRecommendationDBInitializer.java
  bank/src/main/resources/application.properties
Labels: enhancement

#64 Доделал статистику. При добавлении и удалении все ОК
  bank/src/main/java/ru/starbank/bank/controller/RecommendationController.java
  bank/src/main/java/ru/starbank/bank/dto/DynamicRecommendationDTO.java
  bank/src/main/java/ru/starbank/bank/dto/UserDTO.java
  bank/src/main/java/ru/starbank/bank/exceptions/StaticRecommendationInitializerException.java
  bank/src/main/java/ru/starbank/bank/model/DynamicRecommendation.java
  bank/src/main/java/ru/starbank/bank/model/Statistic.java
  bank/src/main/java/ru/starbank/bank/repository/StatisticRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/RecommendationService.java
  bank/src/main/java/ru/starbank/bank/staticRecommendations/StaticRecommendationDBInitializer.java
  bank/src/main/resources/liquibase/script/changes.sql
Labels: enhancement

#66 telegramBot
  bank/pom.xml
  bank/src/main/java/ru/starbank/bank/listener/TelegramBotUpdatesListener.java
  bank/src/main/java/ru/starbank/bank/telegram/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/TelegramBotConfiguration.java
  bank/src/main/resources/application.properties
Labels: enhancement

#69 telegramBot_1
  bank/src/main/java/ru/starbank/bank/StarBankApplication.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/telegram/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/MessageSender.java
  bank/src/main/java/ru/starbank/bank/telegram/listener/TelegramBotUpdatesListener.java
  bank/src/main/resources/application.properties
Labels: enhancement

#68 Enums AND Check full DynamicRecommendation
  bank/src/main/java/ru/starbank/bank/model/enums/QueryEnum.java
  bank/src/main/java/ru/starbank/bank/model/enums/TypeOfProductEnum.java
  bank/src/main/java/ru/starbank/bank/service/Impl/CheckCorrect.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
Labels: enhancement

#74 70 cache 20
  bank/pom.xml
  bank/src/main/java/ru/starbank/bank/StarBankApplication.java
  bank/src/main/java/ru/starbank/bank/cache/CacheConfig.java
  bank/src/main/java/ru/starbank/bank/cache/CacheController.java
  bank/src/main/java/ru/starbank/bank/cache/CacheService.java
  bank/src/main/java/ru/starbank/bank/configuration/CacheConfigurations.java
  bank/src/main/java/ru/starbank/bank/controller/ManagementController.java
  bank/src/main/java/ru/starbank/bank/dto/mapper/ListUserRecommendationsMapper.java
  bank/src/main/java/ru/starbank/bank/model/DynamicRecommendation.java
  bank/src/main/java/ru/starbank/bank/model/Rule.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/ManagementServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationActiveUserOfRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationUserOfRuleServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/ManagementService.java
  bank/src/main/resources/application.properties
Labels: enhancement

#77 telegramBot_3
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/telegram/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/listener/TelegramBotUpdatesListener.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageSender.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageService.java
  bank/src/main/java/ru/starbank/bank/telegram/service/impl/MessageSenderImpl.java
  bank/src/main/java/ru/starbank/bank/telegram/service/impl/MessageServiceImpl.java
Labels: enhancement

#78 Cache is working!
  bank/src/main/java/ru/starbank/bank/StarBankApplication.java
  bank/src/main/java/ru/starbank/bank/configuration/CacheConfigurations.java
  bank/src/main/java/ru/starbank/bank/dto/UserDTO.java
  bank/src/main/java/ru/starbank/bank/dto/UserRecommendationsDTO.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/service/Impl/ManagementServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/RecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/service/impl/MessageServiceImpl.java
Labels: enhancement

#79 Create TGBot DTO and TGBotDTO mapper
  bank/src/main/java/ru/starbank/bank/dto/TelegramRecommendationDTO.java
  bank/src/main/java/ru/starbank/bank/dto/mapper/TelegramRecommendationsMapper.java
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageProcessor.java
  bank/src/main/java/ru/starbank/bank/telegram/service/MessageService.java
  bank/src/main/java/ru/starbank/bank/telegram/service/impl/MessageServiceImpl.java
  bank/src/main/resources/application.properties
Labels: enhancement

#80 UnitTests
  .idea/misc.xml
  bank/src/main/java/ru/starbank/bank/repository/TransactionsRepository.java
  bank/src/main/resources/application.properties
  bank/src/test/java/ru/starbank/bank/repository/TransactionsRepositoryTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/CheckRecommendationByUserIdServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/CheckRecommendationServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/CheckRuleServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/ManagementServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/RecommendationActiveUserOfRuleServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/RecommendationServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/RecommendationTransactionSumCompareRuleServiceImplTests.java
  bank/src/test/java/ru/starbank/bank/service/impl/RecommendationUserOfRuleServiceImplTests.java
Labels: Test

#81 ManagementControllerTest
  bank/src/main/java/ru/starbank/bank/exceptions/NetworkException.java
  bank/src/test/java/ru/starbank/bank/TestController/ManagementControllerTest.java
  bank/src/test/java/ru/starbank/bank/cacheTest/CacheConfigurationsTest.java
  bank/transaction.mv.db
  bank/transaction.trace.db
  transaction.mv.db
Labels: Test

#85 New pull
  README.md
  bank/pom.xml
  bank/src/main/java/ru/starbank/bank/dto/DynamicRecommendationDTO.java
  bank/src/main/java/ru/starbank/bank/service/Impl/CheckRecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/transactionsTest.mv.db
  bank/src/test/java/ru/starbank/bank/TestController/ManagementControllerTest.java
  bank/src/test/java/ru/starbank/bank/TestController/RecommendationControllerTest.java
  bank/src/test/java/ru/starbank/bank/cacheTest/CacheConfigurationsTest.java
  bank/src/test/java/ru/starbank/bank/repository/TransactionsRepositoryTests.java
  bank/src/test/java/ru/starbank/bank/service/Impl/RecommendationActiveUserOfRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/Impl/RecommendationTransactionSumCompareRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/Impl/RecommendationUserOfRuleServiceImplTest.java
  bank/transaction.mv.db
  bank/transaction.trace.db
  transaction.mv.db
Labels: Test

#87 50 unit tests
  bank/src/main/java/ru/starbank/bank/controller/ManagementController.java
  bank/src/main/java/ru/starbank/bank/exceptions/ArgumentsSizeException.java
  bank/src/main/java/ru/starbank/bank/exceptions/EmptyRuleArgumentsException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectComparisonSymbolException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectNumberForComparisonException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectProductTypeException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectRuleORArgumentException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectRuleQueryException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectRuleQueryValueException.java
  bank/src/main/java/ru/starbank/bank/exceptions/IncorrectTransactionTypeException.java
  bank/src/main/java/ru/starbank/bank/exceptions/QueryNullPointerException.java
  bank/src/main/java/ru/starbank/bank/service/Impl/CheckRecommendationByUserIdServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/CheckRecommendationServiceImpl.java
  bank/src/main/java/ru/starbank/bank/service/Impl/CheckRuleServiceImpl.java
  bank/src/test/java/ru/starbank/bank/cacheTest/CacheConfigurationsTest.java
  bank/src/test/java/ru/starbank/bank/service/checkRecommendation/CheckRecommendationByUserIdServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/checkRecommendation/CheckRecommendationByUserIdServiceImplUnitTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/RecommendationActiveUserOfRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/RecommendationTransactionSumCompareRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/RecommendationUserOfRuleServiceImplTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/unit/RecommendationActiveUserOfRuleServiceImplUnitTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/unit/RecommendationTransactionSumCompareDepositWithdrawRuleServiceImplUnitTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/unit/RecommendationTransactionSumCompareRuleServiceImplUnitTest.java
  bank/src/test/java/ru/starbank/bank/service/ruleSets/unit/RecommendationUserOfRuleServiceImplUnitTest.java
  bank/transaction.trace.db
  transaction.mv.db
Labels: Test
